name: clip-env-v2
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - pip
  - pytorch=1.13.1
  - torchvision=0.14.1
  - torchaudio=0.13.1
  - cpuonly
  - numpy=1.21.6
  - pandas=1.5.3
  - pillow=9.5.0
  - scikit-learn=1.1.3
  - pip:
    - transformers==4.21.3
    - azure-ai-ml==1.11.0
    - azure-identity==1.12.0
    - azure-core==1.26.4
    - requests==2.28.2
    - python-dotenv==0.21.1
